In [11]:
import pandas as pd
import numpy as np

import sys
sys.path.insert(0, '../../data/pipeline/run/10_sbdb/')

import importlib

importlib.reload(scoring)
import scoring

In [8]:
asteroid_null= pd.read_csv("../data/interim/asteroid_null_spec_B.csv", index_col='id', usecols=['id','albedo','diameter','H','GM','dv','moid','ad','a','q','closeness'])
asteroid_null.shape

(791309, 10)

In [42]:
asteroid_null[np.isnan(asteroid_null.dv)].shape

(2727, 9)

In [3]:
asteroid_null_predictions= pd.read_csv("../data/interim/asteroid_null_spec_B_predictions.csv")
asteroid_null_predictions.shape

(791309, 26)

In [10]:
asteroid_null_predictions.columns

Index(['spec_B.A', 'spec_B.B', 'spec_B.C', 'spec_B.Cb', 'spec_B.Cg',
       'spec_B.Cgh', 'spec_B.Ch', 'spec_B.D', 'spec_B.K', 'spec_B.L',
       'spec_B.Ld', 'spec_B.O', 'spec_B.Q', 'spec_B.R', 'spec_B.S',
       'spec_B.Sa', 'spec_B.Sk', 'spec_B.Sl', 'spec_B.Sq', 'spec_B.Sr',
       'spec_B.T', 'spec_B.V', 'spec_B.X', 'spec_B.Xc', 'spec_B.Xe',
       'spec_B.Xk'],
      dtype='object')

In [4]:
asteroid_null_predictions.index = asteroid_null.index

In [44]:
asteroid_null_predictions.head(10)

,spec_B.A,spec_B.B,spec_B.C,spec_B.Cb,spec_B.Cg,spec_B.Cgh,spec_B.Ch,spec_B.D,spec_B.K,spec_B.L,...,spec_B.Sk,spec_B.Sl,spec_B.Sq,spec_B.Sr,spec_B.T,spec_B.V,spec_B.X,spec_B.Xc,spec_B.Xe,spec_B.Xk
id,,,,,,,,,,,,,,,,,,,,,
a0000008,0.036801,0.036981,0.037263,0.036896,0.036920,0.036781,0.038394,0.036755,0.038012,0.037809,...,0.036853,0.040840,0.040008,0.036864,0.036951,0.036836,0.037277,0.038353,0.037014,0.036975
a0000009,0.037630,0.038852,0.038973,0.037728,0.037752,0.037609,0.039259,0.037583,0.038868,0.041584,...,0.037683,0.037901,0.037887,0.037694,0.037784,0.037666,0.038993,0.040060,0.037848,0.041232
a0000036,0.037079,0.040291,0.048295,0.041082,0.037199,0.037058,0.038919,0.038026,0.037361,0.037408,...,0.037131,0.037346,0.037332,0.037142,0.037230,0.037114,0.044635,0.037974,0.037845,0.040628
a0000053,0.036659,0.039835,0.047749,0.040617,0.036778,0.036639,0.049008,0.036614,0.036938,0.036984,...,0.036711,0.036924,0.036909,0.036722,0.036809,0.036694,0.044130,0.039027,0.038479,0.037938
a0000068,0.036695,0.036875,0.037156,0.036790,0.036814,0.036675,0.036749,0.036649,0.040671,0.037700,...,0.036747,0.040723,0.039892,0.036758,0.036845,0.036730,0.038815,0.038243,0.036908,0.036868
a0000072,0.037254,0.038464,0.038583,0.037350,0.037374,0.039102,0.049803,0.037207,0.041290,0.038659,...,0.037307,0.037522,0.037508,0.037317,0.037406,0.037289,0.039840,0.039659,0.037470,0.038078
a0000073,0.036674,0.036854,0.038649,0.036769,0.036793,0.036654,0.036728,0.036629,0.036953,0.038057,...,0.036726,0.040700,0.039870,0.038155,0.036824,0.036709,0.038793,0.038222,0.036887,0.036848
a0000086,0.036724,0.039906,0.047833,0.040689,0.036843,0.036704,0.049095,0.036679,0.037003,0.037050,...,0.036776,0.036989,0.036975,0.036787,0.036874,0.036759,0.044208,0.037611,0.037483,0.040240
a0000097,0.037454,0.040699,0.037925,0.037552,0.037576,0.037434,0.037510,0.037408,0.037739,0.037787,...,0.037508,0.037725,0.040718,0.037518,0.037607,0.037490,0.045087,0.039873,0.042571,0.038463
a0000126,0.036830,0.037010,0.037293,0.036925,0.036949,0.036809,0.036884,0.036784,0.040820,0.037838,...,0.036882,0.040872,0.038016,0.036893,0.036980,0.036865,0.037306,0.038384,0.037043,0.037004

In [5]:
def nan_to_empty(row):
    return {x : '' if np.isreal(y) and np.isnan(y) else y for x,y in row.to_dict().items()}

In [12]:
for spec_col in asteroid_null_predictions.columns:
    spec = spec_col.split('.')[1]
    print(spec)
    asteroid_null['spec'] = spec    
        
    asteroid_null['price'] = asteroid_null.apply(lambda row: scoring.price(nan_to_empty(row))[0], axis=1)
    
    asteroid_null['profit_'+spec] = asteroid_null.apply(lambda row: scoring.profit(nan_to_empty(row)), axis=1)
        
    print(asteroid_null['profit_'+spec].describe())

A
count    791309.0
mean          0.0
std           0.0
min           0.0
25%           0.0
50%           0.0
75%           0.0
max           0.0
Name: profit_A, dtype: float64
B
count    7.913090e+05
mean     1.162068e+15
std      1.849028e+17
min     -3.491584e+18
25%      9.859261e+10
50%      3.140265e+11
75%      1.157651e+12
max      1.157877e+20
Name: profit_B, dtype: float64
C
count    7.913090e+05
mean     1.165310e+15
std      1.854186e+17
min     -3.501324e+18
25%      9.886764e+10
50%      3.149025e+11
75%      1.160837e+12
max      1.161107e+20
Name: profit_C, dtype: float64
Cb
count    7.913090e+05
mean     1.163688e+15
std      1.851605e+17
min     -3.496450e+18
25%      9.873001e+10
50%      3.144642e+11
75%      1.159218e+12
max      1.159491e+20
Name: profit_Cb, dtype: float64
Cg
count    7.913090e+05
mean     1.165310e+15
std      1.854186e+17
min     -3.501324e+18
25%      9.886764e+10
50%      3.149025e+11
75%      1.160717e+12
max      1.161107e+20
Name: profit_Cg, dtype: float64
Cgh
count    7.913090e+05
mean     1.165310e+15
std      1.854186e+17
min     -3.501324e+18
25%      9.886764e+10
50%      3.149025e+11
75%      1.160757e+12
max      1.161107e+20
Name: profit_Cgh, dtype: float64
Ch
count    7.913090e+05
mean     1.165310e+15
std      1.854186e+17
min     -3.501324e+18
25%      9.886764e+10
50%      3.149025e+11
75%      1.160853e+12
max      1.161107e+20
Name: profit_Ch, dtype: float64
D
count    7.913090e+05
mean     3.108815e+08
std      4.946598e+10
min     -9.340833e+11
25%      2.637591e+04
50%      8.400971e+04
75%      3.096819e+05
max      3.097601e+13
Name: profit_D, dtype: float64
K
count    7.913090e+05
mean     2.285210e+15
std      3.636123e+17
min     -6.866217e+18
25%      1.938829e+11
50%      6.175052e+11
75%      2.270403e+12
max      2.276971e+20
Name: profit_K, dtype: float64
L
count    7.913090e+05
mean     6.856232e+14
std      1.090932e+17
min     -2.060045e+18
25%      5.816994e+10
50%      1.852766e+11
75%      6.812072e+11
max      6.831508e+19
Name: profit_L, dtype: float64
Ld
count    7.913090e+05
mean     1.958923e-40
std      3.116949e-38
min     -5.885843e-37
25%      1.661998e-44
50%      5.293617e-44
75%      1.946266e-43
max      1.951860e-35
Name: profit_Ld, dtype: float64
O
count    7.913090e+05
mean     4.897367e+15
std      7.792466e+17
min     -1.471478e+19
25%      4.155045e+11
50%      1.323420e+12
75%      4.866011e+12
max      4.879707e+20
Name: profit_O, dtype: float64
Q
count    7.913090e+05
mean     3.569596e+11
std      5.679780e+13
min     -1.072533e+15
25%      3.028534e+07
50%      9.645682e+07
75%      3.546468e+08
max      3.556726e+16
Name: profit_Q, dtype: float64
R
count    7.913090e+05
mean     2.654340e-40
std      4.223466e-38
min     -7.975317e-37
25%      2.252008e-44
50%      7.172509e-44
75%      2.637142e-43
max      2.644770e-35
Name: profit_R, dtype: float64
S
count    7.913090e+05
mean     2.654340e-40
std      4.223466e-38
min     -7.975317e-37
25%      2.252008e-44
50%      7.172498e-44
75%      2.637142e-43
max      2.644770e-35
Name: profit_S, dtype: float64
Sa
count    7.913090e+05
mean     1.327170e-40
std      2.111733e-38
min     -3.987659e-37
25%      1.126004e-44
50%      3.586249e-44
75%      1.318571e-43
max      1.322385e-35
Name: profit_Sa, dtype: float64
Sk
count    7.913090e+05
mean     2.654340e-40
std      4.223466e-38
min     -7.975317e-37
25%      2.252008e-44
50%      7.172498e-44
75%      2.637142e-43
max      2.644770e-35
Name: profit_Sk, dtype: float64
Sl
count    7.913090e+05
mean     2.654340e-40
std      4.223466e-38
min     -7.975317e-37
25%      2.252008e-44
50%      7.172498e-44
75%      2.637142e-43
max      2.644770e-35
Name: profit_Sl, dtype: float64
Sq
count    7.913090e+05
mean     2.654340e-40
std      4.223466e-38
min     -7.975317e-37
25%      2.252008e-44
50%      7.172524e-44
75%      2.637142e-43
max      2.644770e-35
Name: profit_Sq, dtype: float64
Sr
count    7.913090e+05
mean     2.654340e-40
std      4.223466e-38
min     -7.975317e-37
25%      2.252008e-44
50%      7.172498e-44
75%      2.637142e-43
max      2.644770e-35
Name: profit_Sr, dtype: float64
T
count    7.913090e+05
mean     1.621990e+09
std      2.580834e+11
min     -4.873478e+12
25%      1.376135e+05
50%      4.383115e+05
75%      1.615759e+06
max      1.616140e+14
Name: profit_T, dtype: float64
V
count    7.913090e+05
mean     2.654340e-40
std      4.223466e-38
min     -7.975317e-37
25%      2.252008e-44
50%      7.172509e-44
75%      2.637142e-43
max      2.644770e-35
Name: profit_V, dtype: float64
X
count    7.913090e+05
mean     1.963186e+14
std      3.123731e+16
min     -5.898651e+17
25%      1.665615e+10
50%      5.305136e+10
75%      1.950616e+11
max      1.956107e+19
Name: profit_X, dtype: float64
Xc
count    7.913090e+05
mean     2.159078e+14
std      3.435426e+16
min     -6.487235e+17
25%      1.831815e+10
50%      5.834498e+10
75%      2.145255e+11
max      2.151293e+19
Name: profit_Xc, dtype: float64
Xe
count    7.913090e+05
mean     1.963186e+14
std      3.123731e+16
min     -5.898651e+17
25%      1.665615e+10
50%      5.305136e+10
75%      1.950660e+11
max      1.956107e+19
Name: profit_Xe, dtype: float64
Xk
count    7.913090e+05
mean     1.963186e+14
std      3.123731e+16
min     -5.898651e+17
25%      1.665615e+10
50%      5.305136e+10
75%      1.950542e+11
max      1.956107e+19
Name: profit_Xk, dtype: float64

In [15]:
profits_df = asteroid_null.merge(asteroid_null_predictions,left_index=True,right_index=True)
profits_df.shape

(791309, 64)

In [17]:
def expected_profit(row):
    value = 0
    for spec_col in asteroid_null_predictions.columns:
        profit_col = 'profit_'+ spec_col.split('.')[1]
        value += row[profit_col]*row[spec_col]
        
    return value

profits_df['expected_profit'] = profits_df.apply(expected_profit, axis=1)

In [18]:
profits_df.sort_values(by='expected_profit',ascending=False).head(10)

,GM,H,a,ad,albedo,closeness,diameter,dv,moid,q,...,spec_B.Sl,spec_B.Sq,spec_B.Sr,spec_B.T,spec_B.V,spec_B.X,spec_B.Xc,spec_B.Xe,spec_B.Xk,expected_profit
id,,,,,,,,,,,,,,,,,,,,,
a0090482,NaN,2.2,39.266312,48.068028,NaN,2601.076312,NaN,13.161494,29.5152,30.464597,...,0.037657,0.046169,0.040595,0.037540,0.038449,0.039206,0.037765,0.037605,0.040453,5.913082e+19
a0050000,NaN,2.4,43.691575,45.419688,NaN,2601.157386,NaN,12.604644,40.9561,41.963462,...,0.037867,0.040872,0.040820,0.037749,0.038663,0.039424,0.037975,0.037813,0.040678,4.709855e+19
a0020000,NaN,3.6,42.781297,45.096907,0.07,2601.067751,900.0,13.253012,39.5070,40.465686,...,0.037455,0.037441,0.039388,0.037339,0.037222,0.039769,0.038085,0.039879,0.038010,2.273185e+19
a0055636,NaN,3.4,43.145731,48.553825,NaN,2601.024104,NaN,14.047995,36.7342,37.737637,...,0.037792,0.040791,0.040740,0.037675,0.038587,0.039346,0.037900,0.040238,0.040598,1.060243e+19
a0202421,NaN,3.5,43.218299,49.583515,NaN,2601.026973,NaN,13.961492,35.9054,36.853083,...,0.037674,0.038609,0.040613,0.037557,0.038466,0.039223,0.037782,0.040112,0.038412,9.256185e+18
a0208996,NaN,3.6,39.362155,46.554605,NaN,2601.157484,NaN,12.604174,31.1553,32.169706,...,0.037867,0.040872,0.040820,0.037749,0.038663,0.039424,0.037975,0.037813,0.040678,8.974779e+18
a0028978,NaN,3.6,39.791253,49.479365,NaN,2601.096736,NaN,12.979060,29.1485,30.103140,...,0.037710,0.040702,0.038938,0.037593,0.038502,0.039260,0.039019,0.037657,0.038448,8.677129e+18
a0307261,NaN,3.6,42.011534,47.848421,NaN,2601.088095,NaN,13.051023,35.2024,36.174648,...,0.037645,0.040633,0.040582,0.037528,0.038437,0.039193,0.038953,0.037592,0.038382,8.614493e+18
a0055637,NaN,3.6,42.491996,48.413029,NaN,2601.069997,NaN,13.227917,35.6433,36.570962,...,0.037945,0.040956,0.040905,0.037827,0.038743,0.039505,0.038053,0.037892,0.038688,8.563201e+18
a0145452,NaN,3.7,41.631587,42.658718,NaN,2601.043925,NaN,13.586362,39.6023,40.604455,...,0.037738,0.038675,0.040682,0.037621,0.038531,0.039290,0.037846,0.040180,0.038477,7.227702e+18

In [23]:
profits_df[ ~np.isnan(profits_df['albedo'])& ~np.isnan(profits_df['diameter']) & ~np.isnan(profits_df['dv'])].sort_values(by='expected_profit',ascending=False).head(10)

,GM,H,a,ad,albedo,closeness,diameter,dv,moid,q,...,spec_B.Sl,spec_B.Sq,spec_B.Sr,spec_B.T,spec_B.V,spec_B.X,spec_B.Xc,spec_B.Xe,spec_B.Xk,expected_profit
id,,,,,,,,,,,,,,,,,,,,,
a0020000,NaN,3.60,42.781297,45.096907,0.070,2601.067751,900.000,13.253012,39.50700,40.465686,...,0.037455,0.037441,0.039388,0.037339,0.037222,0.039769,0.038085,0.039879,0.038010,2.273185e+19
a0015789,NaN,7.00,39.419335,46.805676,0.022,2601.294873,328.000,12.121680,31.01990,32.032995,...,0.037261,0.045683,0.039183,0.037145,0.037029,0.044533,0.039383,0.037209,0.038285,1.182139e+18
a0000451,NaN,6.65,3.059950,3.289514,0.085,2634.751745,253.900,11.499120,1.85076,2.830386,...,0.037243,0.037229,0.037040,0.037127,0.037011,0.044512,0.039364,0.037741,0.040516,5.944844e+17
a0095626,NaN,6.90,23.257089,28.503082,0.053,2601.104595,230.500,12.940707,17.00120,18.011096,...,0.037275,0.037261,0.039199,0.037160,0.037044,0.044550,0.037902,0.039688,0.040551,3.880295e+17
a0000624,NaN,7.20,5.259580,5.382025,0.025,2611.585365,225.000,13.652932,4.14513,5.137134,...,0.037864,0.037850,0.037658,0.037747,0.037629,0.045254,0.040021,0.038370,0.038905,3.407423e+17
a0000334,NaN,7.70,3.890299,3.981728,0.041,2622.635949,198.770,11.703702,2.78295,3.798870,...,0.037375,0.038422,0.038606,0.037259,0.037143,0.044669,0.038003,0.037874,0.040659,2.775530e+17
a0005145,NaN,7.10,20.392786,32.007110,0.044,2601.166330,190.000,12.826178,7.79583,8.778463,...,0.037505,0.037490,0.037300,0.037388,0.037271,0.044824,0.038135,0.037452,0.040800,2.204438e+17
a0054598,NaN,7.50,16.432841,19.706088,0.050,2601.096675,187.500,13.799298,12.18690,13.159594,...,0.037331,0.037317,0.039257,0.037215,0.037099,0.044617,0.039457,0.037279,0.040612,1.961056e+17
a0000488,NaN,7.81,3.167263,3.669207,0.047,2634.656069,168.117,10.790715,1.70416,2.665319,...,0.037660,0.037646,0.037454,0.037543,0.037426,0.038634,0.041158,0.038163,0.039778,1.843880e+17
a0000566,NaN,8.10,3.376078,3.778984,0.039,2630.977065,167.381,10.767657,1.97895,2.973172,...,0.037040,0.037026,0.036838,0.036925,0.036810,0.044269,0.040481,0.037535,0.040295,1.826923e+17

In [22]:
profits_df[~np.isnan(profits_df['GM']) & ~np.isnan(profits_df['albedo'])& ~np.isnan(profits_df['diameter'])].sort_values(by='expected_profit',ascending=False).head(10)

,GM,H,a,ad,albedo,closeness,diameter,dv,moid,q,...,spec_B.Sl,spec_B.Sq,spec_B.Sr,spec_B.T,spec_B.V,spec_B.X,spec_B.Xc,spec_B.Xe,spec_B.Xk,expected_profit
id,,,,,,,,,,,,,,,,,,,,,
a0000204,0.040105,8.89,2.670566,3.136094,0.1940,2643.143053,48.566,NaN,1.202360,2.205037,...,0.037823,0.045159,0.036632,0.036719,0.036604,0.038682,0.038112,0.036782,0.036743,1.335931e+14
a0000138,0.032898,8.75,2.448294,2.846994,0.2730,2648.225331,52.905,NaN,1.038070,2.049593,...,0.038058,0.040003,0.036860,0.036947,0.036832,0.038923,0.038349,0.037010,0.036971,1.103927e+14
a0000126,0.031430,9.27,2.438405,2.698135,0.1723,2647.931287,44.820,NaN,1.172730,2.178676,...,0.040872,0.038016,0.036893,0.036980,0.036865,0.037306,0.038384,0.037043,0.037004,1.054987e+14
a0000212,0.880836,8.28,3.124040,3.443751,0.0465,2633.497453,136.120,NaN,1.819750,2.804330,...,0.037063,0.037048,0.036860,0.036948,0.036832,0.044296,0.037686,0.037558,0.040320,3.121374e+09
a0000324,0.663074,6.82,2.681447,3.594894,0.0500,2646.150802,220.691,NaN,0.784536,1.768000,...,0.036859,0.037892,0.036658,0.036745,0.036630,0.044053,0.038959,0.037352,0.040099,2.360002e+09
a0000009,0.581969,6.28,2.385637,2.679342,0.1180,2649.418151,190.000,NaN,1.106910,2.091931,...,0.037901,0.037887,0.037694,0.037784,0.037666,0.038993,0.040060,0.037848,0.041232,2.008867e+09
a0000137,0.510485,8.05,3.123352,3.784847,0.0650,2634.848863,128.678,NaN,1.488530,2.461857,...,0.037381,0.037366,0.037176,0.038149,0.037148,0.038347,0.039510,0.037880,0.037934,1.813724e+09
a0000008,0.511745,6.49,2.201764,2.546339,0.2260,2654.741330,147.491,NaN,0.874176,1.857190,...,0.040840,0.040008,0.036864,0.036951,0.036836,0.037277,0.038353,0.037014,0.036975,1.715531e+09
a0000053,0.375690,8.81,2.616774,3.154697,0.0310,2644.792950,90.893,NaN,1.099740,2.078850,...,0.036924,0.036909,0.036722,0.036809,0.036694,0.044130,0.039027,0.038479,0.037938,1.351558e+09
a0000036,0.288274,8.46,2.746824,3.584347,0.0360,2643.891982,115.204,NaN,0.959267,1.909301,...,0.037346,0.037332,0.037142,0.037230,0.037114,0.044635,0.037974,0.037845,0.040628,1.012653e+09

In [24]:
profits_df.to_csv("../data/interim/asteroid_null_spec_B_predictions_profits.csv")